name: 'List Sub Folders'
description: 'Get a json list of the folder listed in the specified folder'
inputs:
  path:
    description: 'Folder to list'
    required: true
outputs:
  folders: # id of output
    description: 'A JSON formatted list of folders'
    value: ${{ steps.set-folders.outputs.folders }}
runs:
  using: 'composite'
  steps:
    - run: apt update && apt install tree jq -y
      shell: bash
    - id: set-folders
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
      run: |
        cd "$INPUT_PATH"
        folders=$(tree -J -d -L 1 | jq -c '.[0].contents | map(.name)')
        echo "$folders"
        safe_folders=$(printf '%s' "$folders" | tr -d '\n\r')
        echo "folders=$safe_folders" >> "$GITHUB_OUTPUT"
